### ISSUE TITLE
Microphone animation

### ISSUE THREAD

**Issue by DaryaMager** [easably/speech-demo#23]
Description:
Create an animation of the microphone when you press the button, it should pulse. If the user releases the button, it returns to its original position.
https://www.figma.com/file/1NoQ8SRXDnrubFQSBIfx37/eLang-TV-app?node-id=6516%3A2116

![image](https://user-images.githubusercontent.com/85741367/135231110-1edf5aad-b83e-41ec-90a9-ca97352a9f8a.png)

@katjafolezhinskaja

**Comment by onelblone** [comment]
[mic.zip](https://github.com/easably/speech-demo/files/7251475/mic.zip)
