### ISSUE TITLE
Draw a prototype design with speech recognition in the style of the elang-TV app

### ISSUE THREAD

**Issue by DaryaMager** [easably/speech-demo#5]
Description:
Draw a prototype design with speech recognition in the style of the lang-TV app

**Comment by katjafolezhinskaja** [comment]
Концепт дизайна для спич рикогнишен https://www.figma.com/file/1NoQ8SRXDnrubFQSBIfx37/eLang-TV-app?node-id=6580%3A2645

**Comment by katjafolezhinskaja** [comment]
@NikaPipchenko @annamaksimik гляньте, плиз, то, что мы мучали в пятницу долго с Сергеем

**Comment by NikaPipchenko** [comment]
Если мы будем это внедрять в тв, то кнопка должна быть синяя ( как и цвет всех кнопок)

**Comment by NikaPipchenko** [comment]
На счёт 100% успеха и попробовать снова точно нет.

Смотри флоу.
Я закончила на 100% и как мне вернуться к списку песен? ( Эту кнопку нужно добавить)

**Comment by NikaPipchenko** [comment]
И если я отвечу на 20% успешности котик по логике вещей должен быть грустный?
Я если на 10 , то злой?
